ci(eval): print readable test report

diff --git a/.github/workflows/flake_evaltests.yml b/.github/workflows/flake_evaltests.yml
--- a/.github/workflows/flake_evaltests.yml
+++ b/.github/workflows/flake_evaltests.yml
@@ -27,5 +27,11 @@ jobs:
 
       - name: Run Nix Flake Eval Tests
         run: |
-          echo 'Flake Eval Tests'
-          nix eval .#evalTests --show-trace --print-build-logs --verbose
+          nix --quiet eval .#evalTestReportText --raw --show-trace
+
+          result="$(nix --quiet eval .#evalTests --show-trace)"
+          if [ "$result" != "true" ]; then
+            echo "Evaluation tests failed. Inspect details with:"
+            echo "  nix eval .#evalTestResults --show-trace"
+            exit 1
+          fi
